[package]
name = "impl_cast"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["extra-traits", "full"] }
quote = "1.0"

[features]
debug = [
] # If enabled it will add std::fmt::Debug as a trait bound to device_traits
