name: Build and deploy
on:
    push:
        branches:
            - master
            - feature/**
        tags:
            - v*.*.*

jobs:
    build:
        uses: dreaded_x/workflows/.gitea/workflows/docker-kubernetes.yaml@ef78704b98c72e4a6b8340f9bff7b085a7bdd95c
        secrets: inherit
        with:
            push_manifests: false

    deploy:
        name: Deploy container
        runs-on: ubuntu-latest
        container: catthehacker/ubuntu:act-latest
        needs: build
        if: gitea.ref == 'refs/heads/master'
        steps:
            - name: Stop and remove current container
              run: |
                  docker stop automation_rs || true
                  docker rm automation_rs || true

            - name: Create container
              run: |
                  docker create \
                    --pull always \
                    --restart unless-stopped \
                    --name automation_rs \
                    --network mqtt \
                    -e RUST_LOG=automation=debug \
                    -e AUTOMATION__SECRETS__MQTT_PASSWORD=${{ secrets.MQTT_PASSWORD }} \
                    -e AUTOMATION__SECRETS__HUE_TOKEN=${{ secrets.HUE_TOKEN }} \
                    -e AUTOMATION__SECRETS__NTFY_TOPIC=${{ secrets.NTFY_TOPIC }} \
                    $(echo ${{ toJSON(needs.build.outputs.images) }} | jq .automation -r)

                  docker network connect web automation_rs

            - name: Start container
              run: docker start automation_rs
