name: Build and deploy
on:
    push:
        branches:
            - master
            - feature/**
        tags:
            - v*.*.*

jobs:
    build:
        uses: dreaded_x/workflows/.gitea/workflows/rust-kubernetes.yaml@22ee0c1788a8d2157db87d6a6f8dbe520fe48592
        secrets: inherit
        with:
            upload_manifests: false

    deploy:
        name: Deploy container
        runs-on: ubuntu-latest
        container: catthehacker/ubuntu:act-latest
        needs: build
        if: gitea.ref == 'refs/heads/master'
        steps:
            - name: Stop and remove current container
              run: |
                  docker stop automation_rs || true
                  docker rm automation_rs || true

            - name: Create container
              run: |
                  docker create \
                    --pull always \
                    --restart unless-stopped \
                    --name automation_rs \
                    --network mqtt \
                    -e RUST_LOG=automation=debug \
                    -e MQTT_PASSWORD=${{ secrets.MQTT_PASSWORD }} \
                    -e HUE_TOKEN=${{ secrets.HUE_TOKEN }} \
                    -e NTFY_TOPIC=${{ secrets.NTFY_TOPIC }} \
                    git.huizinga.dev/dreaded_x/automation_rs@${{ needs.build.outputs.digest }}

                  docker network connect web automation_rs

            - name: Start container
              run: docker start automation_rs
