[openid]
base_url = "https://login.huizinga.dev/api/oidc"

[mqtt]
host = "olympus.vpn.huizinga.dev"
port = 8883
client_name = "automation-ares"
username = "mqtt"
password = "${MQTT_PASSWORD}"
tls = true

[ntfy]
topic = "${NTFY_TOPIC}"

[presence]
topic = "automation_dev/presence/+/#"

[debug_bridge]
topic = "automation_dev/debug"

[light_sensor]
topic = "zigbee2mqtt_dev/living/light"
min = 23_000
max = 25_000

[devices.kitchen_kettle]
type = "IkeaOutlet"
outlet_type = "Kettle"
name = "Kettle"
room = "Kitchen"
topic = "zigbee2mqtt/kitchen/kettle"
timeout = 5

[devices.workbench_charger]
type = "IkeaOutlet"
outlet_type = "Charger"
name = "Charger"
room = "Workbench"
topic = "zigbee2mqtt/workbench/charger"
timeout = 5

[devices.workbench_outlet]
type = "IkeaOutlet"
name = "Outlet"
room = "Workbench"
topic = "zigbee2mqtt/workbench/outlet"

[devices.living_zeus]
type = "WakeOnLAN"
name = "Zeus"
room = "Living Room"
topic = "automation/appliance/living_room/zeus"
mac_address = "30:9c:23:60:9c:13"

[devices.hallway_frontdoor]
type = "ContactSensor"
topic = "zigbee2mqtt/hallway/frontdoor"
presence = { timeout = 10 }
