[openid]
base_url = "https://login.huizinga.dev/api/oidc"

[mqtt]
host = "mosquitto"
port = 8883
client_name = "automation_rs"
username = "mqtt"
password = "${MQTT_PASSWORD}"

[ntfy]
topic = "${NTFY_TOPIC}"

[presence]
topic = "automation/presence/+/#"

[hue_bridge]
ip = "10.0.0.146"
login = "${HUE_TOKEN}"
flags = { presence = 41, darkness = 43 }

[debug_bridge]
topic = "automation/debug"

[light_sensor]
topic = "zigbee2mqtt/living/light"
min = 22_000
max = 23_500

[devices.kitchen_kettle]
type = "IkeaOutlet"
outlet_type = "Kettle"
name = "Kettle"
room = "Kitchen"
topic = "zigbee2mqtt/kitchen/kettle"
timeout = 300

[devices.bathroom_light]
type = "IkeaOutlet"
outlet_type = "Light"
name = "Light"
room = "Bathroom"
topic = "zigbee2mqtt/bathroom/light"
timeout = 2700

[devices.workbench_charger]
type = "IkeaOutlet"
outlet_type = "Charger"
name = "Charger"
room = "Workbench"
topic = "zigbee2mqtt/workbench/charger"
timeout = 72000

[devices.workbench_outlet]
type = "IkeaOutlet"
name = "Outlet"
room = "Workbench"
topic = "zigbee2mqtt/workbench/outlet"

[devices.living_zeus]
type = "WakeOnLAN"
name = "Zeus"
room = "Living Room"
topic = "automation/appliance/living_room/zeus"
mac_address = "30:9c:23:60:9c:13"
broadcast_ip = "10.0.0.255"

[devices.living_mixer]
type = "KasaOutlet"
ip = "10.0.0.49"

[devices.living_speakers]
type = "KasaOutlet"
ip = "10.0.0.182"

[devices.living_audio]
type = "AudioSetup"
topic = "zigbee2mqtt/living/remote"
mixer = "living_mixer"
speakers = "living_speakers"

[devices.hallway_frontdoor]
type = "ContactSensor"
topic = "zigbee2mqtt/hallway/frontdoor"
presence = { timeout = 900 }
