[openid]
base_url = "https://login.huizinga.dev/api/oidc"

[mqtt]
host = "mosquitto"
port = 8883
client_name = "automation_rs"
username = "mqtt"
password = "${MQTT_PASSWORD}"

[ntfy]
topic = "${NTFY_TOPIC}"

[presence]
topic = "automation/presence/+/#"

# Devices
[device.debug_bridge]
type = "DebugBridge"
topic = "automation/debug"

[device.hue_bridge]
type = "HueBridge"
ip = "10.0.0.146"
login = "${HUE_TOKEN}"
flags = { presence = 41, darkness = 43 }


[device.living_light_sensor]
type = "LightSensor"
topic = "zigbee2mqtt/living/light"
min = 22_000
max = 23_500

[device.living_zeus]
type = "WakeOnLAN"
name = "Zeus"
room = "Living Room"
topic = "automation/appliance/living_room/zeus"
mac_address = "30:9c:23:60:9c:13"
broadcast_ip = "10.0.0.255"

[device.living_mixer]
type = "KasaOutlet"
ip = "10.0.0.49"

[device.living_speakers]
type = "KasaOutlet"
ip = "10.0.0.182"

[device.living_audio]
type = "AudioSetup"
topic = "zigbee2mqtt/living/remote"
mixer = "living_mixer"
speakers = "living_speakers"


[device.kitchen_kettle]
type = "IkeaOutlet"
outlet_type = "Kettle"
name = "Kettle"
room = "Kitchen"
topic = "zigbee2mqtt/kitchen/kettle"
timeout = 300


[device.bathroom_light]
type = "IkeaOutlet"
outlet_type = "Light"
name = "Light"
room = "Bathroom"
topic = "zigbee2mqtt/bathroom/light"
timeout = 2700

[device.bathroom_washer]
type = "Washer"
topic = "zigbee2mqtt/bathroom/washer"
threshold = 1


[device.workbench_charger]
type = "IkeaOutlet"
outlet_type = "Charger"
name = "Charger"
room = "Workbench"
topic = "zigbee2mqtt/workbench/charger"
timeout = 72000

[device.workbench_outlet]
type = "IkeaOutlet"
name = "Outlet"
room = "Workbench"
topic = "zigbee2mqtt/workbench/outlet"


[device.hallway_lights]
type = "HueGroup"
ip = "10.0.0.146"
login = "${HUE_TOKEN}"
group_id = 81
scene_id = "3qWKxGVadXFFG4o"
timer_id = 1
remotes = [{ topic = "zigbee2mqtt/hallway/remote" }]

[device.hallway_frontdoor]
type = "ContactSensor"
topic = "zigbee2mqtt/hallway/frontdoor"
presence = { topic = "automation/presence/contact/frontdoor", timeout = 900 }
trigger = { devices = ["hallway_lights"], timeout = 60 }
