[openid]
base_url = "https://login.huizinga.dev/api/oidc"

[mqtt]
host="mosquitto"
port=8883
client_name="automation_rs"
username="mqtt"
password="${MQTT_PASSWORD}"

[ntfy]
topic = "${NTFY_TOPIC}"

[presence]
topic = "automation/presence/+/#"

[hue_bridge]
ip = "10.0.0.146"
login = "${HUE_TOKEN}"
flags = { presence = 41, darkness = 43 }

[debug_bridge]
topic = "automation/debug"

[light_sensor]
topic = "zigbee2mqtt/living/light"
min = 19_000
max = 22_000

[devices.kitchen_kettle]
type = "IkeaOutlet"
name = "Kettle"
room = "Kitchen"
topic = "zigbee2mqtt/kitchen/kettle"
kettle = { timeout = 300 }

[devices.living_workbench]
type = "IkeaOutlet"
name = "Workbench"
room = "Living Room"
topic = "zigbee2mqtt/living/workbench"

[devices.living_zeus]
type = "WakeOnLAN"
name = "Zeus"
room = "Living Room"
topic = "automation/appliance/living_room/zeus"
mac_address = "30:9c:23:60:9c:13"

[devices.living_audio]
type = "AudioSetup"
topic = "zigbee2mqtt/living/remote"
[devices.living_audio.mixer]
type = "KasaOutlet"
ip = "10.0.0.49"
[devices.living_audio.speakers]
type = "KasaOutlet"
ip = "10.0.0.182"

[devices.hallway_frontdoor]
type = "ContactSensor"
topic = "zigbee2mqtt/hallway/frontdoor"
presence = { timeout = 900 }
