[openid]
base_url = "https://login.huizinga.dev/api/oidc"

[mqtt]
host="olympus.lan.huizinga.dev"
port=8883
username="mqtt"
password="${MQTT_PASSWORD}"

[ntfy]
topic = "${NTFY_TOPIC}"

[presence]
topic = "automation_dev/presence"

[hue_bridge]
ip = "10.0.0.146"
login = "yPZs07rEirWOKkDhAO6ggCMT9T4Xb-FJYnqnTOLF"
flags = { presence = 41, darkness = 43 }

[light_sensor]
topic = "zigbee2mqtt_dev/living/light"
min = 23_000
max = 25_000

[devices.kitchen_kettle]
type = "IkeaOutlet"
name = "Kettle"
room = "Kitchen"
topic = "zigbee2mqtt/kitchen/kettle"
kettle = { timeout = 5 }

[devices.living_workbench]
type = "IkeaOutlet"
name = "Workbench"
room = "Living Room"
topic = "zigbee2mqtt/living/workbench"

[devices.living_zeus]
type = "WakeOnLAN"
name = "Zeus"
room = "Living Room"
topic = "automation/appliance/living_room/zeus"
mac_address = "30:9c:23:60:9c:13"

[devices.audio]
type = "AudioSetup"
topic = "zigbee2mqtt/living/remote"
mixer = "10.0.0.49"
speakers = "10.0.0.182"

[devices.hallway_frontdoor]
type = "ContactSensor"
topic = "zigbee2mqtt/hallway/frontdoor"
# @TODO This should be automatically constructed from the identifier and presence topic
presence = { topic = "automation_dev/presence/frontdoor", timeout = 10 }
