[openid]
base_url = "https://login.huizinga.dev/api/oidc"

[mqtt]
host = "olympus.lan.huizinga.dev"
port = 8883
client_name = "automation-zeus"
username = "mqtt"
password = "${MQTT_PASSWORD}"
tls = true

[ntfy]
topic = "${NTFY_TOPIC}"

[presence]
topic = "automation_dev/presence/+/#"

[hue_bridge]
ip = "10.0.0.146"
login = "${HUE_TOKEN}"
flags = { presence = 41, darkness = 43 }

[debug_bridge]
topic = "automation_dev/debug"

[light_sensor]
topic = "zigbee2mqtt_dev/living/light"
min = 23_000
max = 25_000

[devices.kitchen_kettle]
type = "IkeaOutlet"
outlet_type = "Kettle"
name = "Kettle"
room = "Kitchen"
topic = "zigbee2mqtt/kitchen/kettle"
timeout = 5

[devices.bathroom_light]
type = "IkeaOutlet"
outlet_type = "Light"
name = "Bathroom light"
room = "Bathroom"
topic = "zigbee2mqtt/bathroom/light"
timeout = 60

[devices.workbench_charger]
type = "IkeaOutlet"
outlet_type = "Charger"
name = "Charger"
room = "Workbench"
topic = "zigbee2mqtt/workbench/charger"
timeout = 5

[devices.workbench_outlet]
type = "IkeaOutlet"
name = "Outlet"
room = "Workbench"
topic = "zigbee2mqtt/workbench/outlet"

[devices.living_zeus]
type = "WakeOnLAN"
name = "Zeus"
room = "Living Room"
topic = "automation/appliance/living_room/zeus"
mac_address = "30:9c:23:60:9c:13"

[devices.living_mixer]
type = "KasaOutlet"
ip = "10.0.0.49"

[devices.living_speakers]
type = "KasaOutlet"
ip = "10.0.0.182"

[devices.living_audio]
type = "AudioSetup"
topic = "zigbee2mqtt/living/remote"
mixer = "living_mixer"
speakers = "living_speakers"

[devices.hallway_frontdoor]
type = "ContactSensor"
topic = "zigbee2mqtt/hallway/frontdoor"
presence = { timeout = 10 }
lights = { lights = ["bathroom_light"], timeout = 10 }

[devices.bathroom_washer]
type = "Washer"
topic = "zigbee2mqtt/bathroom/washer"
