openid:
    base_url: "https://login.huizinga.dev/api/oidc"

mqtt:
    host: "olympus.lan.huizinga.dev"
    port: 8883
    client_name: "automation-zeus"
    username: "mqtt"
    password: "${MQTT_PASSWORD}"
    tls: true

ntfy:
    topic: "${NTFY_TOPIC}"

presence:
    topic: "automation_dev/presence/+/#"

devices:
    debug_bridge:
        !DebugBridge
        topic: "automation_dev/debug"

    hue_bridge:
        !HueBridge
        ip: &hue_ip "10.0.0.146"
        login: &hue_token "${HUE_TOKEN}"
        flags: { presence: 41, darkness: 43 }


    living_light_sensor:
        !LightSensor
        topic: "zigbee2mqtt_dev/living/light"
        min: 23000
        max: 25000

    living_zeus:
        !WakeOnLAN
        name: "Zeus"
        room: "Living Room"
        topic: "automation/appliance/living_room/zeus"
        mac_address: "30:9c:23:60:9c:13"

    &mixer living_mixer:
        !KasaOutlet
        ip: "10.0.0.49"

    &speakers living_speakers:
        !KasaOutlet
        ip: "10.0.0.182"

    living_audio:
        !AudioSetup
        topic: "zigbee2mqtt/living/remote"
        mixer: *mixer
        speakers: *speakers


    kitchen_kettle:
        !IkeaOutlet
        outlet_type: "Kettle"
        name: "Kettle"
        room: "Kitchen"
        topic: "zigbee2mqtt/kitchen/kettle"
        timeout: 5
        remotes:
        - topic: "zigbee2mqtt/bedroom/remote"
        - topic: "zigbee2mqtt/kitchen/remote"


    bathroom_light:
        !IkeaOutlet
        type: "IkeaOutlet"
        outlet_type: "Light"
        name: "Light"
        room: "Bathroom"
        topic: "zigbee2mqtt/bathroom/light"
        timeout: 60

    bathroom_washer:
        !Washer
        topic: "zigbee2mqtt/bathroom/washer"
        threshold: 1

    workbench_charger:
        !IkeaOutlet
        outlet_type: "Charger"
        name: "Charger"
        room: "Workbench"
        topic: "zigbee2mqtt/workbench/charger"
        timeout: 5

    workbench_outlet:
        !IkeaOutlet
        name: "Outlet"
        room: "Workbench"
        topic: "zigbee2mqtt/workbench/outlet"


    hallway_lights:
        !HueGroup
        ip: *hue_ip
        login: *hue_token
        group_id: 81
        scene_id: "3qWKxGVadXFFG4o"
        timer_id: 1
        remotes:
        - topic: "zigbee2mqtt/hallway/remote"

    hallway_frontdoor:
        !ContactSensor
        topic: "zigbee2mqtt/hallway/frontdoor"
        presence:
            topic: "automation_dev/presence/contact/frontdoor"
            timeout: 10
        trigger:
            devices: ["hallway_lights"]
            timeout: 10


    bedroom_air_filter:
        !AirFilter
        name: "Air Filter"
        room: "Bedroom"
        topic: "pio/filter/test"
