[openid]
base_url = "https://login.huizinga.dev/api/oidc"

[mqtt]
host = "olympus.lan.huizinga.dev"
port = 8883
client_name = "automation-zeus"
username = "mqtt"
password = "${MQTT_PASSWORD}"
tls = true

[ntfy]
topic = "${NTFY_TOPIC}"

[presence]
topic = "automation_dev/presence/+/#"

# Devices
[device.debug_bridge]
type = "DebugBridge"
topic = "automation_dev/debug"

[device.hue_bridge]
type = "HueBridge"
ip = "10.0.0.146"
login = "${HUE_TOKEN}"
flags = { presence = 41, darkness = 43 }


[device.living_light_sensor]
type = "LightSensor"
topic = "zigbee2mqtt_dev/living/light"
min = 23_000
max = 25_000
# TODO: Implement this:
trigger = ["hue_bridge", "debug_bridge"]

[device.living_zeus]
type = "WakeOnLAN"
name = "Zeus"
room = "Living Room"
topic = "automation/appliance/living_room/zeus"
mac_address = "30:9c:23:60:9c:13"

[device.living_mixer]
type = "KasaOutlet"
ip = "10.0.0.49"

[device.living_speakers]
type = "KasaOutlet"
ip = "10.0.0.182"

[device.living_audio]
type = "AudioSetup"
topic = "zigbee2mqtt/living/remote"
mixer = "living_mixer"
speakers = "living_speakers"


[device.kitchen_kettle]
type = "IkeaOutlet"
outlet_type = "Kettle"
name = "Kettle"
room = "Kitchen"
topic = "zigbee2mqtt/kitchen/kettle"
timeout = 5


[device.bathroom_light]
type = "IkeaOutlet"
outlet_type = "Light"
name = "Bathroom light"
room = "Bathroom"
topic = "zigbee2mqtt/bathroom/light"
timeout = 60

[device.bathroom_washer]
type = "Washer"
topic = "zigbee2mqtt/bathroom/washer"
threshold = 1


[device.workbench_charger]
type = "IkeaOutlet"
outlet_type = "Charger"
name = "Charger"
room = "Workbench"
topic = "zigbee2mqtt/workbench/charger"
timeout = 5

[device.workbench_outlet]
type = "IkeaOutlet"
name = "Outlet"
room = "Workbench"
topic = "zigbee2mqtt/workbench/outlet"


[device.hallway_light]
type = "HueLight"
ip = "10.0.0.146"
login = "${HUE_TOKEN}"
light_id = 16
timer_id = 1

[device.hallway_frontdoor]
type = "ContactSensor"
topic = "zigbee2mqtt/hallway/frontdoor"
presence = { topic = "automation_dev/presence/contact/frontdoor", timeout = 10 }
trigger = { devices = ["hallway_light"], timeout = 10 }
